INSERT INTO TICKETSTATUS VALUES (1, 'Active'); 
INSERT INTO TICKETSTATUS VALUES (2, 'Closed'); 
INSERT INTO TICKETSTATUS VALUES (3, 'Resolved'); 
INSERT INTO TICKETSTATUS VALUES (4, 'WFC'); 

INSERT INTO TICKETTYPE VALUES (1, 'Incident'); 
INSERT INTO TICKETTYPE VALUES (2, 'Service Request'); 
INSERT INTO TICKETTYPE VALUES (3, 'Problem Record'); 


INSERT INTO TICKET_WORKER VALUES (1,'Axxx Bxxx' 'Anu'); 
INSERT INTO TICKET_WORKER VALUES (2,'Gxxx Xxxx' 'Gou'); 
INSERT INTO TICKET_WORKER VALUES (3,'Cxxx Dxxx' 'Tam'); 
INSERT INTO TICKET_WORKER VALUES (4,'Exxx Fxxx' 'bis'); 

INSERT INTO APPLICATIONS VALUES (1, 'APP1'); 
INSERT INTO APPLICATIONS VALUES (2, 'APP2'); 
INSERT INTO APPLICATIONS VALUES (3, 'APP3'); 

INSERT INTO TICKET_APP_CATEGORY VALUES (1, 'Admin'); 
INSERT INTO TICKET_APP_CATEGORY VALUES (2, 'External'); 
INSERT INTO TICKET_APP_CATEGORY VALUES (3, 'External Europe'); 

INSERT INTO TICKET_DEFECT_AREA VALUES (1, 'UI'); 
INSERT INTO TICKET_DEFECT_AREA VALUES (2, 'Backend'); 
INSERT INTO TICKET_DEFECT_AREA VALUES (3, 'DB'); 

INSERT INTO TICKET_ENVIRONMENT VALUES (1, 'PROD'); 
INSERT INTO TICKET_ENVIRONMENT VALUES (2, 'PP'); 
INSERT INTO TICKET_ENVIRONMENT VALUES (3, 'QA'); 

INSERT INTO "PUBLIC"."TEAM_MEMBER"("TEAM_MEMBER_ID")VALUES(1);

INSERT INTO "PUBLIC"."TEAM_MEMBER_APPRAISAL"("TEAM_MEMBER_APPRAISAL_ID","FINANCIAL_YEAR","LEAVE_COUNT","TEAM_MEMBER_ID")VALUES(1,'2024',0,1);
