INSERT INTO TICKETSTATUS VALUES (1, 'Active'); 
INSERT INTO TICKETSTATUS VALUES (2, 'Closed'); 
INSERT INTO TICKETSTATUS VALUES (3, 'Resolved'); 
INSERT INTO TICKETSTATUS VALUES (4, 'WFC'); 

INSERT INTO TICKETTYPE VALUES (1, 'Incident'); 
INSERT INTO TICKETTYPE VALUES (2, 'Service Request'); 
INSERT INTO TICKETTYPE VALUES (3, 'Problem Record'); 


INSERT INTO WORKERS VALUES (1, 'Anu'); 
INSERT INTO WORKERS VALUES (2, 'Pam'); 
INSERT INTO WORKERS VALUES (3, 'Gou'); 
INSERT INTO WORKERS VALUES (4, 'Tam'); 

INSERT INTO APPLICATIONS VALUES (1, 'APP1'); 
INSERT INTO APPLICATIONS VALUES (2, 'APP2'); 
INSERT INTO APPLICATIONS VALUES (3, 'APP3'); 
